### ISSUE TITLE
Plan for v1.1

### ISSUE THREAD

**Issue by obenjiro** [SimplePEG/SimplePEG#1]
1) We have an ability to interpret PEG parser, but we need to add ability to create pure / precompiled modules. It will increase speed and reduce file size
- [ ] Python module generation ( https://github.com/SimplePEG/Python/issues/1 )
- [x] JavaScript module generation ( https://github.com/SimplePEG/JavaScript/issues/1 )

2) We need to increase test coverage and cover a lot more negative cases
- [ ] Basic Unit Test for Python RD parser ( https://github.com/SimplePEG/Python/issues/2 )
- [ ] Negative Cases Python ( https://github.com/SimplePEG/Python/issues/3 )
- [x] Negative Cases JavaScript ( https://github.com/SimplePEG/JavaScript/issues/2 )

3) More documentation
- [x] More detailed README for JavaScript ( https://github.com/SimplePEG/JavaScript/issues/3 )
- [x] More detailed README for Python ( https://github.com/SimplePEG/Python/issues/4 )
- [ ] More detailed README for SimplePEG ( https://github.com/SimplePEG/SimplePEG/issues/2 )
- [ ] Python source code documentation ( https://github.com/SimplePEG/Python/issues/5 )
- [ ] JSDoc Code documentation for JavaScript ( https://github.com/SimplePEG/JavaScript/issues/4 )

4) Marketing
- [ ] SimplePEG logo
- [x] SimplePEG website
- [x] SimplePEG gitter account
- [x] SimplePEG online playground
